# Generated by Django 5.0.6 on 2024-07-12 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_veiculo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="marca",
            old_name="nacionalicade",
            new_name="nacionalidade",
        ),
    ]
